/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { useQuery, useSuspenseQuery } from "@tanstack/react-query";
import { devtoolsFetch } from "../../devtools-fetch";
import type { GetProviderImpactResponse } from "../model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
	query: T,
	queryKey: K,
): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

export const getGetDevtoolsImpactUrl = () => {
	return `/__devtools/impact`;
};

/**
 * Analyzes git changes to determine which providers are affected
 * @summary Get provider impact analysis
 */
export const getDevtoolsImpact = async (
	options?: RequestInit,
): Promise<GetProviderImpactResponse> => {
	return devtoolsFetch<GetProviderImpactResponse>(getGetDevtoolsImpactUrl(), {
		...options,
		method: "GET",
	});
};

export const getGetDevtoolsImpactQueryKey = () => {
	return [`/__devtools/impact`] as const;
};

export const getGetDevtoolsImpactQueryOptions = <
	TData = Awaited<ReturnType<typeof getDevtoolsImpact>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getDevtoolsImpact>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof devtoolsFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetDevtoolsImpactQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getDevtoolsImpact>>
	> = ({ signal }) => getDevtoolsImpact({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getDevtoolsImpact>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDevtoolsImpactQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDevtoolsImpact>>
>;
export type GetDevtoolsImpactQueryError = unknown;

export function useGetDevtoolsImpact<
	TData = Awaited<ReturnType<typeof getDevtoolsImpact>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsImpact>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDevtoolsImpact>>,
					TError,
					Awaited<ReturnType<typeof getDevtoolsImpact>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof devtoolsFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsImpact<
	TData = Awaited<ReturnType<typeof getDevtoolsImpact>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsImpact>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDevtoolsImpact>>,
					TError,
					Awaited<ReturnType<typeof getDevtoolsImpact>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof devtoolsFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsImpact<
	TData = Awaited<ReturnType<typeof getDevtoolsImpact>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsImpact>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof devtoolsFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get provider impact analysis
 */

export function useGetDevtoolsImpact<
	TData = Awaited<ReturnType<typeof getDevtoolsImpact>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsImpact>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof devtoolsFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDevtoolsImpactQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return withQueryKey(query, queryOptions.queryKey);
}

export const getGetDevtoolsImpactSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getDevtoolsImpact>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseSuspenseQueryOptions<
			Awaited<ReturnType<typeof getDevtoolsImpact>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof devtoolsFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetDevtoolsImpactQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getDevtoolsImpact>>
	> = ({ signal }) => getDevtoolsImpact({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getDevtoolsImpact>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDevtoolsImpactSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDevtoolsImpact>>
>;
export type GetDevtoolsImpactSuspenseQueryError = unknown;

export function useGetDevtoolsImpactSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsImpact>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsImpact>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof devtoolsFetch>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsImpactSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsImpact>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsImpact>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof devtoolsFetch>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsImpactSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsImpact>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsImpact>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof devtoolsFetch>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get provider impact analysis
 */

export function useGetDevtoolsImpactSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsImpact>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsImpact>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof devtoolsFetch>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDevtoolsImpactSuspenseQueryOptions(options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}
