/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */
import type { InvokeHandlerBodyKind } from "./invokeHandlerBodyKind";

export interface InvokeHandlerBody {
	scopeModuleId: string;
	kind: (typeof InvokeHandlerBodyKind)[keyof typeof InvokeHandlerBodyKind];
	handlerKey: string;
	payload: unknown;
	executionContext?: unknown;
	includePreHandlerKeys?: string[];
}
