/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */
import type { DynamicModuleInfo } from "./dynamicModuleInfo";
import type { ModuleGraphEntrypoint } from "./moduleGraphEntrypoint";
import type { ModuleGraphMessageRef } from "./moduleGraphMessageRef";
import type { ModuleGraphNodeBase } from "./moduleGraphNodeBase";
import type { ModuleGraphNodeCommandHandlerKeys } from "./moduleGraphNodeCommandHandlerKeys";
import type { ModuleGraphNodeCommandPreHandlerClassNames } from "./moduleGraphNodeCommandPreHandlerClassNames";
import type { ModuleGraphNodeCommandPreHandlerLifetimeTypes } from "./moduleGraphNodeCommandPreHandlerLifetimeTypes";
import type { ModuleGraphNodeControllerLifetimeTypes } from "./moduleGraphNodeControllerLifetimeTypes";
import type { ModuleGraphNodeInitializerClassNames } from "./moduleGraphNodeInitializerClassNames";
import type { ModuleGraphNodeInterceptorClassNames } from "./moduleGraphNodeInterceptorClassNames";
import type { ModuleGraphNodeInterceptorDecoratorNames } from "./moduleGraphNodeInterceptorDecoratorNames";
import type { ModuleGraphNodeKind } from "./moduleGraphNodeKind";
import type { ModuleGraphNodeLifetimeTypes } from "./moduleGraphNodeLifetimeTypes";
import type { ModuleGraphNodeProviderAllowCircular } from "./moduleGraphNodeProviderAllowCircular";
import type { ModuleGraphNodeProviderClassNames } from "./moduleGraphNodeProviderClassNames";
import type { ModuleGraphNodeProviderDependencies } from "./moduleGraphNodeProviderDependencies";
import type { ModuleGraphNodeProviderEager } from "./moduleGraphNodeProviderEager";
import type { ModuleGraphNodeProviderInitAfter } from "./moduleGraphNodeProviderInitAfter";
import type { ModuleGraphNodeProviderIsClass } from "./moduleGraphNodeProviderIsClass";
import type { ModuleGraphNodeProviderIsFactory } from "./moduleGraphNodeProviderIsFactory";
import type { ModuleGraphNodeProviderValues } from "./moduleGraphNodeProviderValues";
import type { ModuleGraphNodeQueryHandlerKeys } from "./moduleGraphNodeQueryHandlerKeys";
import type { ModuleGraphNodeQueryPreHandlerClassNames } from "./moduleGraphNodeQueryPreHandlerClassNames";
import type { ModuleGraphNodeQueryPreHandlerLifetimeTypes } from "./moduleGraphNodeQueryPreHandlerLifetimeTypes";
import type { ModuleGraphOperationRef } from "./moduleGraphOperationRef";
import type { ModuleGraphRoute } from "./moduleGraphRoute";
import type { ModuleProviderImpact } from "./moduleProviderImpact";

export interface ModuleGraphNode {
	id: string;
	name: string;
	baseName?: string;
	dynamic?: DynamicModuleInfo;
	grouped: boolean;
	familyInstanceCount: number;
	instanceCount: number;
	kind: ModuleGraphNodeKind;
	dependencyCount: number;
	dependentCount: number;
	providers: string[];
	providerAllowCircular: ModuleGraphNodeProviderAllowCircular;
	providerIsClass: ModuleGraphNodeProviderIsClass;
	providerIsFactory: ModuleGraphNodeProviderIsFactory;
	providerClassNames: ModuleGraphNodeProviderClassNames;
	providerValues: ModuleGraphNodeProviderValues;
	providerDependencies: ModuleGraphNodeProviderDependencies;
	providerEager: ModuleGraphNodeProviderEager;
	providerInitAfter: ModuleGraphNodeProviderInitAfter;
	lifetimeTypes: ModuleGraphNodeLifetimeTypes;
	exports: string[];
	controllers: string[];
	controllerLifetimeTypes: ModuleGraphNodeControllerLifetimeTypes;
	queryHandlers: string[];
	commandHandlers: string[];
	queryHandlerKeys: ModuleGraphNodeQueryHandlerKeys;
	commandHandlerKeys: ModuleGraphNodeCommandHandlerKeys;
	queryPreHandlers: string[];
	queryPreHandlerExports: string[];
	commandPreHandlers: string[];
	commandPreHandlerExports: string[];
	queryPreHandlerClassNames: ModuleGraphNodeQueryPreHandlerClassNames;
	commandPreHandlerClassNames: ModuleGraphNodeCommandPreHandlerClassNames;
	queryPreHandlerLifetimeTypes: ModuleGraphNodeQueryPreHandlerLifetimeTypes;
	commandPreHandlerLifetimeTypes: ModuleGraphNodeCommandPreHandlerLifetimeTypes;
	interceptors: string[];
	interceptorExports: string[];
	interceptorClassNames: ModuleGraphNodeInterceptorClassNames;
	interceptorDecoratorNames: ModuleGraphNodeInterceptorDecoratorNames;
	initializers: string[];
	initializerExports: string[];
	initializerClassNames: ModuleGraphNodeInitializerClassNames;
	entrypoints: ModuleGraphEntrypoint[];
	ownOperationIds: string[];
	calledOperations: ModuleGraphOperationRef[];
	publishedMessageTypes: string[];
	subscribedMessages: ModuleGraphMessageRef[];
	routes: ModuleGraphRoute[];
	instances: ModuleGraphNodeBase[];
	impact: ModuleProviderImpact;
}
