/**
 * Generated by orval v8.18.0
 * Do not edit manually.
 */

export type ModuleGraphOperationRef =
	| {
			serviceName: string;
			operationId: string;
			transport: "http";
	  }
	| {
			serviceName: string;
			transport: "messaging";
			type: string;
	  };
