/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */
import type { DynamicModuleInfo } from "./dynamicModuleInfo";
import type { ModuleGraphEntrypoint } from "./moduleGraphEntrypoint";
import type { ModuleGraphMessageRef } from "./moduleGraphMessageRef";
import type { ModuleGraphNodeBaseCommandHandlerKeys } from "./moduleGraphNodeBaseCommandHandlerKeys";
import type { ModuleGraphNodeBaseCommandPreHandlerClassNames } from "./moduleGraphNodeBaseCommandPreHandlerClassNames";
import type { ModuleGraphNodeBaseCommandPreHandlerLifetimeTypes } from "./moduleGraphNodeBaseCommandPreHandlerLifetimeTypes";
import type { ModuleGraphNodeBaseControllerLifetimeTypes } from "./moduleGraphNodeBaseControllerLifetimeTypes";
import type { ModuleGraphNodeBaseInitializerClassNames } from "./moduleGraphNodeBaseInitializerClassNames";
import type { ModuleGraphNodeBaseInterceptorClassNames } from "./moduleGraphNodeBaseInterceptorClassNames";
import type { ModuleGraphNodeBaseInterceptorDecoratorNames } from "./moduleGraphNodeBaseInterceptorDecoratorNames";
import type { ModuleGraphNodeBaseLifetimeTypes } from "./moduleGraphNodeBaseLifetimeTypes";
import type { ModuleGraphNodeBaseProviderAllowCircular } from "./moduleGraphNodeBaseProviderAllowCircular";
import type { ModuleGraphNodeBaseProviderClassNames } from "./moduleGraphNodeBaseProviderClassNames";
import type { ModuleGraphNodeBaseProviderDependencies } from "./moduleGraphNodeBaseProviderDependencies";
import type { ModuleGraphNodeBaseProviderEager } from "./moduleGraphNodeBaseProviderEager";
import type { ModuleGraphNodeBaseProviderInitAfter } from "./moduleGraphNodeBaseProviderInitAfter";
import type { ModuleGraphNodeBaseProviderIsClass } from "./moduleGraphNodeBaseProviderIsClass";
import type { ModuleGraphNodeBaseProviderIsFactory } from "./moduleGraphNodeBaseProviderIsFactory";
import type { ModuleGraphNodeBaseProviderValues } from "./moduleGraphNodeBaseProviderValues";
import type { ModuleGraphNodeBaseQueryHandlerKeys } from "./moduleGraphNodeBaseQueryHandlerKeys";
import type { ModuleGraphNodeBaseQueryPreHandlerClassNames } from "./moduleGraphNodeBaseQueryPreHandlerClassNames";
import type { ModuleGraphNodeBaseQueryPreHandlerLifetimeTypes } from "./moduleGraphNodeBaseQueryPreHandlerLifetimeTypes";
import type { ModuleGraphNodeKind } from "./moduleGraphNodeKind";
import type { ModuleGraphOperationRef } from "./moduleGraphOperationRef";

export interface ModuleGraphNodeBase {
	id: string;
	name: string;
	baseName?: string;
	dynamic?: DynamicModuleInfo;
	grouped: boolean;
	familyInstanceCount: number;
	instanceCount: number;
	kind: ModuleGraphNodeKind;
	dependencyCount: number;
	dependentCount: number;
	providers: string[];
	providerAllowCircular: ModuleGraphNodeBaseProviderAllowCircular;
	providerIsClass: ModuleGraphNodeBaseProviderIsClass;
	providerIsFactory: ModuleGraphNodeBaseProviderIsFactory;
	providerClassNames: ModuleGraphNodeBaseProviderClassNames;
	providerValues: ModuleGraphNodeBaseProviderValues;
	providerDependencies: ModuleGraphNodeBaseProviderDependencies;
	providerEager: ModuleGraphNodeBaseProviderEager;
	providerInitAfter: ModuleGraphNodeBaseProviderInitAfter;
	lifetimeTypes: ModuleGraphNodeBaseLifetimeTypes;
	exports: string[];
	controllers: string[];
	controllerLifetimeTypes: ModuleGraphNodeBaseControllerLifetimeTypes;
	queryHandlers: string[];
	commandHandlers: string[];
	queryHandlerKeys: ModuleGraphNodeBaseQueryHandlerKeys;
	commandHandlerKeys: ModuleGraphNodeBaseCommandHandlerKeys;
	queryPreHandlers: string[];
	queryPreHandlerExports: string[];
	commandPreHandlers: string[];
	commandPreHandlerExports: string[];
	queryPreHandlerClassNames: ModuleGraphNodeBaseQueryPreHandlerClassNames;
	commandPreHandlerClassNames: ModuleGraphNodeBaseCommandPreHandlerClassNames;
	queryPreHandlerLifetimeTypes: ModuleGraphNodeBaseQueryPreHandlerLifetimeTypes;
	commandPreHandlerLifetimeTypes: ModuleGraphNodeBaseCommandPreHandlerLifetimeTypes;
	interceptors: string[];
	interceptorExports: string[];
	interceptorClassNames: ModuleGraphNodeBaseInterceptorClassNames;
	interceptorDecoratorNames: ModuleGraphNodeBaseInterceptorDecoratorNames;
	initializers: string[];
	initializerExports: string[];
	initializerClassNames: ModuleGraphNodeBaseInitializerClassNames;
	entrypoints: ModuleGraphEntrypoint[];
	ownOperationIds: string[];
	calledOperations: ModuleGraphOperationRef[];
	publishedMessageTypes: string[];
	subscribedMessages: ModuleGraphMessageRef[];
}
