/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Awilixify Devtools API
 * API for inspecting module graphs, traces, and provider impact
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";

import type {
	ClearTracesResponse,
	DeleteTraceResponse,
	GetTraceResponse,
	GetTracesResponse,
} from "../model";

const withQueryKey = <T extends object, K>(
	query: T,
	queryKey: K,
): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

export const getGetDevtoolsTracesUrl = () => {
	return `/__devtools/traces`;
};

/**
 * Returns all HTTP request traces
 * @summary Get all traces
 */
export const getDevtoolsTraces = async (
	options?: RequestInit,
): Promise<GetTracesResponse> => {
	const res = await fetch(getGetDevtoolsTracesUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: GetTracesResponse = body ? JSON.parse(body) : {};
	return data;
};

export const getGetDevtoolsTracesQueryKey = () => {
	return [`/__devtools/traces`] as const;
};

export const getGetDevtoolsTracesQueryOptions = <
	TData = Awaited<ReturnType<typeof getDevtoolsTraces>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getDevtoolsTraces>>,
			TError,
			TData
		>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetDevtoolsTracesQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getDevtoolsTraces>>
	> = ({ signal }) => getDevtoolsTraces({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getDevtoolsTraces>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDevtoolsTracesQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDevtoolsTraces>>
>;
export type GetDevtoolsTracesQueryError = unknown;

export function useGetDevtoolsTraces<
	TData = Awaited<ReturnType<typeof getDevtoolsTraces>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTraces>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDevtoolsTraces>>,
					TError,
					Awaited<ReturnType<typeof getDevtoolsTraces>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsTraces<
	TData = Awaited<ReturnType<typeof getDevtoolsTraces>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTraces>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDevtoolsTraces>>,
					TError,
					Awaited<ReturnType<typeof getDevtoolsTraces>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsTraces<
	TData = Awaited<ReturnType<typeof getDevtoolsTraces>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTraces>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all traces
 */

export function useGetDevtoolsTraces<
	TData = Awaited<ReturnType<typeof getDevtoolsTraces>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTraces>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDevtoolsTracesQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return withQueryKey(query, queryOptions.queryKey);
}

export const getGetDevtoolsTracesSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getDevtoolsTraces>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseSuspenseQueryOptions<
			Awaited<ReturnType<typeof getDevtoolsTraces>>,
			TError,
			TData
		>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetDevtoolsTracesQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getDevtoolsTraces>>
	> = ({ signal }) => getDevtoolsTraces({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getDevtoolsTraces>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDevtoolsTracesSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDevtoolsTraces>>
>;
export type GetDevtoolsTracesSuspenseQueryError = unknown;

export function useGetDevtoolsTracesSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsTraces>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTraces>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsTracesSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsTraces>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTraces>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsTracesSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsTraces>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTraces>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all traces
 */

export function useGetDevtoolsTracesSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsTraces>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTraces>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDevtoolsTracesSuspenseQueryOptions(options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

export const getDeleteDevtoolsTracesUrl = () => {
	return `/__devtools/traces`;
};

/**
 * Removes all traces from memory and the persisted history file
 * @summary Clear trace history
 */
export const deleteDevtoolsTraces = async (
	options?: RequestInit,
): Promise<ClearTracesResponse> => {
	const res = await fetch(getDeleteDevtoolsTracesUrl(), {
		...options,
		method: "DELETE",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: ClearTracesResponse = body ? JSON.parse(body) : {};
	return data;
};

export const getDeleteDevtoolsTracesMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteDevtoolsTraces>>,
		TError,
		void,
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteDevtoolsTraces>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["deleteDevtoolsTraces"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteDevtoolsTraces>>,
		void
	> = () => {
		return deleteDevtoolsTraces(fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteDevtoolsTracesMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteDevtoolsTraces>>
>;

export type DeleteDevtoolsTracesMutationError = unknown;

/**
 * @summary Clear trace history
 */
export const useDeleteDevtoolsTraces = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteDevtoolsTraces>>,
			TError,
			void,
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteDevtoolsTraces>>,
	TError,
	void,
	TContext
> => {
	return useMutation(
		getDeleteDevtoolsTracesMutationOptions(options),
		queryClient,
	);
};
export const getGetDevtoolsTracesTraceIdUrl = (traceId: string) => {
	return `/__devtools/traces/${traceId}`;
};

/**
 * Returns a specific trace by its ID
 * @summary Get trace by ID
 */
export const getDevtoolsTracesTraceId = async (
	traceId: string,
	options?: RequestInit,
): Promise<GetTraceResponse> => {
	const res = await fetch(getGetDevtoolsTracesTraceIdUrl(traceId), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: GetTraceResponse = body ? JSON.parse(body) : {};
	return data;
};

export const getGetDevtoolsTracesTraceIdQueryKey = (traceId: string) => {
	return [`/__devtools/traces/${traceId}`] as const;
};

export const getGetDevtoolsTracesTraceIdQueryOptions = <
	TData = Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
	TError = unknown,
>(
	traceId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetDevtoolsTracesTraceIdQueryKey(traceId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>
	> = ({ signal }) =>
		getDevtoolsTracesTraceId(traceId, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: traceId !== null && traceId !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDevtoolsTracesTraceIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>
>;
export type GetDevtoolsTracesTraceIdQueryError = unknown;

export function useGetDevtoolsTracesTraceId<
	TData = Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
	TError = unknown,
>(
	traceId: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
					TError,
					Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsTracesTraceId<
	TData = Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
	TError = unknown,
>(
	traceId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
					TError,
					Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsTracesTraceId<
	TData = Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
	TError = unknown,
>(
	traceId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get trace by ID
 */

export function useGetDevtoolsTracesTraceId<
	TData = Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
	TError = unknown,
>(
	traceId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDevtoolsTracesTraceIdQueryOptions(
		traceId,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return withQueryKey(query, queryOptions.queryKey);
}

export const getGetDevtoolsTracesTraceIdSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
	TError = unknown,
>(
	traceId: string,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetDevtoolsTracesTraceIdQueryKey(traceId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>
	> = ({ signal }) =>
		getDevtoolsTracesTraceId(traceId, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDevtoolsTracesTraceIdSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>
>;
export type GetDevtoolsTracesTraceIdSuspenseQueryError = unknown;

export function useGetDevtoolsTracesTraceIdSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
	TError = unknown,
>(
	traceId: string,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsTracesTraceIdSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
	TError = unknown,
>(
	traceId: string,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevtoolsTracesTraceIdSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
	TError = unknown,
>(
	traceId: string,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get trace by ID
 */

export function useGetDevtoolsTracesTraceIdSuspense<
	TData = Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
	TError = unknown,
>(
	traceId: string,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getDevtoolsTracesTraceId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDevtoolsTracesTraceIdSuspenseQueryOptions(
		traceId,
		options,
	);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

export const getDeleteDevtoolsTracesTraceIdUrl = (traceId: string) => {
	return `/__devtools/traces/${traceId}`;
};

/**
 * Removes a single trace from memory and the persisted history
 * @summary Delete trace by ID
 */
export const deleteDevtoolsTracesTraceId = async (
	traceId: string,
	options?: RequestInit,
): Promise<DeleteTraceResponse> => {
	const res = await fetch(getDeleteDevtoolsTracesTraceIdUrl(traceId), {
		...options,
		method: "DELETE",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: DeleteTraceResponse = body ? JSON.parse(body) : {};
	return data;
};

export const getDeleteDevtoolsTracesTraceIdMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteDevtoolsTracesTraceId>>,
		TError,
		{ traceId: string },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteDevtoolsTracesTraceId>>,
	TError,
	{ traceId: string },
	TContext
> => {
	const mutationKey = ["deleteDevtoolsTracesTraceId"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteDevtoolsTracesTraceId>>,
		{ traceId: string }
	> = (props) => {
		const { traceId } = props ?? {};

		return deleteDevtoolsTracesTraceId(traceId, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteDevtoolsTracesTraceIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteDevtoolsTracesTraceId>>
>;

export type DeleteDevtoolsTracesTraceIdMutationError = unknown;

/**
 * @summary Delete trace by ID
 */
export const useDeleteDevtoolsTracesTraceId = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteDevtoolsTracesTraceId>>,
			TError,
			{ traceId: string },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteDevtoolsTracesTraceId>>,
	TError,
	{ traceId: string },
	TContext
> => {
	return useMutation(
		getDeleteDevtoolsTracesTraceIdMutationOptions(options),
		queryClient,
	);
};
